#!/usr/bin/env node
// TEMPLATE - scaffolded by the umbrage-prototype skill, not yet run against a real Figma file.
//
// Copy this into `libs/util/tailwind-preset/sync-tokens.mjs` in an engagement's cloned prototype
// repo (never into the shared nestjs-react-starter starter kit) the first time that engagement
// sets up Design Token Sync. See `references/figma-sync.md` for the full setup steps.
//
// STATUS: this implements the spec documented in figma-sync.md (read Figma Variables, convert
// names, rewrite tailwind.config.js). The name/color conversion and tailwind.config.js
// insert-or-update logic were smoke-tested against a mocked Figma API response (correct hex
// conversion, freeform names skipped with a warning, idempotent re-run with no duplicate blocks) -
// but it has never been run against a *real* Figma file, since no FIGMA_ACCESS_TOKEN or client
// file key was available when this was written. Validate it against your engagement's duplicated
// V2.2 file before trusting its output, and update this comment once it has run successfully for
// the first time against real data.
//
// Usage:
//   FIGMA_ACCESS_TOKEN=your_token FIGMA_FILE_KEY=your_client_file_key node sync-tokens.mjs
//
// Requires a paid Figma plan - the Variables REST API is Professional plan and above.

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TAILWIND_CONFIG_PATH = join(__dirname, 'tailwind.config.js');

const BEGIN_MARKER = '  /* BEGIN FIGMA SYNCED TOKENS - generated by sync-tokens.mjs, do not hand-edit */';
const END_MARKER = '  /* END FIGMA SYNCED TOKENS */';

function requireEnv(name) {
  const value = process.env[name];
  if (!value) {
    console.error(`Missing required env var ${name}. See the Usage comment at the top of this file.`);
    process.exit(1);
  }
  return value;
}

// Converts a Figma Variable name like "light/background/badge/information" into the tailwind
// token key "light-background-badge-information", per the naming convention documented in
// figma-sync.md. Variables that don't follow {mode}/{type}/{component}/{variant} are skipped with
// a warning rather than silently mangled.
function figmaNameToTailwindKey(figmaName) {
  if (!/^[a-z0-9]+(\/[a-z0-9-]+){2,}$/i.test(figmaName)) {
    return null;
  }
  return figmaName.split('/').join('-');
}

// Figma stores colors as 0-1 floats per RGBA channel; tailwind wants hex (with an alpha suffix
// only when the color isn't fully opaque, matching the existing '#25272c88'-style tokens already
// hand-authored elsewhere in tailwind.config.js).
function figmaColorToHex({ r, g, b, a = 1 }) {
  const channel = (v) => Math.round(v * 255).toString(16).padStart(2, '0');
  const hex = `#${channel(r)}${channel(g)}${channel(b)}`;
  return a < 1 ? `${hex}${channel(a)}` : hex;
}

async function fetchLocalVariables(fileKey, token) {
  const res = await fetch(`https://api.figma.com/v1/files/${fileKey}/variables/local`, {
    headers: { 'X-Figma-Token': token },
  });
  if (!res.ok) {
    throw new Error(`Figma API request failed: ${res.status} ${res.statusText}`);
  }
  return res.json();
}

// Only handles solid COLOR variables resolved against each variable's default mode. Variables
// that alias other variables, or that aren't type COLOR, are skipped - extend this function
// before relying on it for typography or spacing tokens.
function extractColorTokens(variablesResponse) {
  const { meta } = variablesResponse;
  const tokens = {};
  for (const variable of Object.values(meta.variables ?? {})) {
    if (variable.resolvedType !== 'COLOR') continue;
    const key = figmaNameToTailwindKey(variable.name);
    if (!key) {
      console.warn(`Skipping variable with unexpected name format: "${variable.name}"`);
      continue;
    }
    const collection = meta.variableCollections[variable.variableCollectionId];
    const defaultModeId = collection?.defaultModeId;
    const value = variable.valuesByMode[defaultModeId];
    if (!value || typeof value !== 'object' || !('r' in value)) continue;
    tokens[key] = figmaColorToHex(value);
  }
  return tokens;
}

function renderTokenBlock(tokens) {
  const lines = Object.entries(tokens)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, hex]) => `    '${key}': '${hex}',`);
  return [BEGIN_MARKER, ...lines, END_MARKER].join('\n');
}

function upsertTokenBlock(configSource, newBlock) {
  const beginIdx = configSource.indexOf(BEGIN_MARKER);
  const endIdx = configSource.indexOf(END_MARKER);
  if (beginIdx !== -1 && endIdx !== -1) {
    return configSource.slice(0, beginIdx) + newBlock + configSource.slice(endIdx + END_MARKER.length);
  }
  // First run: insert the block as the first entries of theme.extend.colors so it's easy to find.
  const colorsOpen = configSource.indexOf('colors: {');
  if (colorsOpen === -1) {
    throw new Error("Couldn't find 'colors: {' in tailwind.config.js - has the file structure changed?");
  }
  const insertAt = colorsOpen + 'colors: {'.length;
  return configSource.slice(0, insertAt) + '\n' + newBlock + configSource.slice(insertAt);
}

async function main() {
  const token = requireEnv('FIGMA_ACCESS_TOKEN');
  const fileKey = requireEnv('FIGMA_FILE_KEY');

  if (fileKey === 'KjT0pvJZg3HrTM2SGxlZxy') {
    console.error(
      'FIGMA_FILE_KEY is set to the shared V2.2 kit, not a client duplicate. ' +
        'Every engagement must sync from its own duplicated file - see SKILL.md.'
    );
    process.exit(1);
  }

  const variablesResponse = await fetchLocalVariables(fileKey, token);
  const tokens = extractColorTokens(variablesResponse);
  const tokenCount = Object.keys(tokens).length;
  if (tokenCount === 0) {
    console.warn('No COLOR variables matched the expected naming convention. Nothing to update.');
    return;
  }

  const configSource = readFileSync(TAILWIND_CONFIG_PATH, 'utf8');
  const updatedSource = upsertTokenBlock(configSource, renderTokenBlock(tokens));
  writeFileSync(TAILWIND_CONFIG_PATH, updatedSource);

  console.log(`Synced ${tokenCount} color token(s) into ${TAILWIND_CONFIG_PATH}`);
  console.log('Review the diff, then commit - this script does not commit or push on its own.');
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
